Fix '_create_instance' in config_unittest
Previously '_create_instance' would initialize the config object every
time it would be called. This causes '_WriteConfig' to fail with
ConfigurationError: The configuration file has been modified since the
last write. Fix this by passing the config object to '_create_instance'
method.

Signed-off-by: Ilias Tsitsimpis <iliastsi@grnet.gr>
Reviewed-by: Jose A. Lopes <jabolopes@google.com>