serializer.Private: fix deepcopy under Python 3
serializer.Private aims at protecting from accidental leakage of
sensitive data, while maintaining ease of use. To this end, it wraps an
existing object and essentially assumes the object's identity,
overriding essentially only __str__ and __repr__. This implementation
works fine in Python 2, however it chokes the copy.deepcopy
implementation of Python 3 by causing infinite recursion:

    File "/usr/share/ganeti/3.0/ganeti/cmdlib/instance_set_params.py", line 818, in _PreCheckDisks
      disks = copy.deepcopy(inst_disks)
    File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
      y = copier(x, memo)
    File "/usr/lib/python3.7/copy.py", line 215, in _deepcopy_list
      append(deepcopy(a, memo))
    File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
      y = _reconstruct(x, memo, *rv)
    File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
      state = deepcopy(state, memo)
    File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
      y = copier(x, memo)
    File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
      y[deepcopy(key, memo)] = deepcopy(value, memo)
    File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
      y = copier(x, memo)
    File "/usr/lib/python3.7/copy.py", line 220, in _deepcopy_tuple
      y = [deepcopy(a, memo) for a in x]
    File "/usr/lib/python3.7/copy.py", line 220, in <listcomp>
      y = [deepcopy(a, memo) for a in x]
    File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
      y = _reconstruct(x, memo, *rv)
    File "/usr/lib/python3.7/copy.py", line 281, in _reconstruct
      if hasattr(y, '__setstate__'):
    File "/usr/share/ganeti/3.0/ganeti/serializer.py", line 279, in __getattr__
      return Private(getattr(self._item, attr),
    File "/usr/share/ganeti/3.0/ganeti/serializer.py", line 279, in __getattr__
      return Private(getattr(self._item, attr),
    File "/usr/share/ganeti/3.0/ganeti/serializer.py", line 279, in __getattr__
      return Private(getattr(self._item, attr),
    [Previous line repeated 483 more times]
  RecursionError: maximum recursion depth exceeded

The infinite recursion is caused by the fact that Private assumes the
original object's __hash__, causing the default deepcopy implementation
to wrap the Private object in itself infinite times. There are two ways
out of this: either drop __hash__ from Private, which will possibly
break code relying on Private objects being hashable, or implement
__copy__ and __deepcopy__ to handle copying ourselves.

To this end, implement __copy__ and __deepcopy__ and create a new
Private instance that wraps the same or a copy of the original object,
respectively.

Signed-off-by: Apollon Oikonomopoulos <apoikos@dmesg.gr>