Handle better broken disks
While running burnin:
  File "/usr/lib/python2.4/site-packages/ganeti/objects.py", line 497, in __str__
    val += ", size=%dm)>" % self.size
TypeError: int argument required

This happened while handling another error, so we lose the original
error information.

So we should try to handle this better.

Reviewed-by: ultrotter